# Generated by Django 3.0.3 on 2020-05-19 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Solar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carga', models.TextField(verbose_name='Carga demandada por el sistema')),
                ('elegir_energia_solar', models.BooleanField(blank=True, null=True, verbose_name='Agregar energía solar')),
                ('tipo_paneles', models.CharField(choices=[(1, 'Panel genérico'), (2, 'Panel Monocristalino'), (3, 'Panel Policristalino')], default='Panel genérico', max_length=255, verbose_name='Seleccione el tipo de panel')),
                ('elegir_generador_eolico', models.BooleanField(blank=True, null=True, verbose_name='Agregar generador eólico')),
                ('tipo_generador_eolico', models.CharField(choices=[(1, 'Generador eólico genérico'), (2, 'Generador eólico horizontal'), (3, 'Generador eólico vertical')], default='Generador eólico genérico', max_length=255, verbose_name='Seleccione el tipo de generador eólico')),
                ('elegir_celda', models.BooleanField(blank=True, null=True, verbose_name='Agregar almacenamiento en Hidrógeno')),
                ('tipo_celda', models.CharField(choices=[(1, 'Celda tipo PEM'), (2, 'Alcalina')], default='Celda tipo PEM', max_length=255, verbose_name='Seleccione el tipo de celda')),
                ('elegir_carga', models.CharField(choices=[(1, 'KWh/día'), (2, 'KWh/mes'), (3, 'KWh')], default='KWh/día', max_length=255, verbose_name='Seleccione el tipo de carga')),
                ('titulo', models.CharField(max_length=50)),
                ('archivo', models.FileField(upload_to='')),
            ],
        ),
    ]
